spin_manifest_version = 2

[application]
name = "{{project-name | kebab_case}}"
version = "0.1.0"
authors = ["{{authors}}"]
description = "{{project-description}}"

[application.trigger.mqtt]
address = "{{mqtt-address}}"
username = "{{mqtt-username}}"
password = "{{mqtt-password}}"
keep_alive_interval = "{{mqtt-keep_alive_interval}}"

[[trigger.mqtt]]
component = "{{project-name | kebab_case}}"
topic = "{{mqtt-topic}}"
qos = "{{mqtt-qos}}"

[component.{{project-name | kebab_case}}]
source = "target/wasm32-wasip2/release/{{project-name | snake_case}}.wasm"
allowed_outbound_hosts = ["{{mqtt-address}}"]
[component.{{project-name | kebab_case}}.build]
command = "cargo build --target wasm32-wasip2 --release"